export const medicines = [
  { name: "APRICLAVE 625 TAB" },
  { name: "ASCOGAIN-MAX SOFT GELATIN CAP" },
  { name: "BESTHEAL ROLL ON OIL" },
  { name: "CISSJOD-M TAB" },
  { name: "ESMOWELL-40 TAB" },
  { name: "ESMOWELL-D CAP" },
  { name: "ESMOWELL-IT TAB" },
  { name: "FARONEST 200 TAB" },
  { name: "FARONEST 300 TAB" },
  { name: "FLIPCEF-500 TAB" },
  { name: "IVPARA-A TAB" },
  { name: "IVPARA-MR TAB" },
  { name: "IVPARA-SP TAB" },
  { name: "IVPARA-TH TAB" },
  { name: "NEOCOXIB 90 TAB" },
  { name: "NEOCOXIB C TAB" },
  { name: "NEOCOXIB TH TAB" },
  { name: "NUZOLID TAB" },
  { name: "RANZEF 200 TAB" },
  { name: "RANZEF O TAB" },
  { name: "REBIROX-DSR CAP" },
  { name: "REBIROX-L CAP" },
  { name: "RISEVEST-500 TAB" },
  { name: "RISEVEST-PLUS TAB" },
  { name: "ROXCAL D3 DROPS" },
  { name: "ROXCAL D3 NANO SHOTS" },
  { name: "ROXCAL D3 SACHET" },
  { name: "ROXCAL TAB" },
  { name: "ROXFIT NT TAB" },
  { name: "ROXFIT PG CAP" },
  { name: "ROXFIT TAB" },
  { name: "ROXRUN PLUS TAB" },
  { name: "RUTOTAS-D TAB" },
  { name: "XENOLEX SYRUP" },
  { name: "YESCORT 30 TAB" },
  { name: "YESCORT 6 TAB" },
  { name: "ZOBADOXIME 200 TAB" },
  { name: "AEROBEST FB 0.5MG ROXPULES" },
  { name: "AEROBEST FB 1.0MG ROXPULES" },
  { name: "APRICLAV FORTE DRY SYRUP" },
  { name: "BUDAMIST 0.5MG ROXPULES" },
  { name: "BUDAMIST 1.0MG ROXPULES" },
  { name: "BUDAMIST-LS ROXPULES" },
  { name: "BUDAMIST-LS KID ROXPULES" },
  { name: "DUALMIST ROXPULES" },
  { name: "DUALMIST-LD ROXPULES" },
  { name: "EMIROX-MD TAB" },
  { name: "ENZIGO LB KID DRY SYRUP" },
  { name: "FLIPNAC INJ" },
  { name: "IMMUVENT DROPS" },
  { name: "IMMUVENT SYRUP" },
  { name: "IVPARA-M-FORTE" },
  { name: "LANZODAC-KID TAB" },
  { name: "NOSENAX NASAL SPRAY" },
  { name: "RANZEF-100 DRY SYRUP" },
  { name: "ROXCAL D3 ORAL SPRAY" },
  { name: "ROXDRYL-A SYRUP" },
  { name: "ROXDRYL-D SYRUP" },
  { name: "ROXDRYL-LS KID SYRUP" },
  { name: "ROXMONT LC KID TAB" },
  { name: "TECHMIST-AF NASAL SPRAY" },
  { name: "TECHMIST-F NASAL SPRAY" },
  { name: "TESLAFIN-M CREAM" },
  { name: "TUMINET OF SYRUP" },
  { name: "TUMIZOB DROPS" },
  { name: "ZOBADOXIME 100 DRY SYRUP" },
  { name: "ZOBADOXIME 100 DT TAB" },
  { name: "AEROBEST FB 200 ROXCAPS" },
  { name: "AEROBEST FB 400 ROXCAPS" },
  { name: "AEROBEST SF 250 ROXCAPS" },
  { name: "BILSEE 20 TAB" },
  { name: "BILSEE M TAB" },
  { name: "FLIPNAC 600 TAB" },
  { name: "GLYCOWORD ROXPULES" },
  { name: "POVINATOR GARGLE" },
  { name: "ROXHALER DPI DEVICE" },
  { name: "ROXMINT 3D TAB" },
  { name: "ROXMONT 10 TAB" },
  { name: "ROXMONT FX TAB" },
  { name: "ROXMONT LC TAB" },
  { name: "YESCORT-6 TAB" },
  { name: "APRICLAV 1.2GM INJ" },
  { name: "DIALCEF INJ" },
  { name: "EMIROX INJ" },
  { name: "ESMOWELL-40 INJ" },
  { name: "FEFORD INJ" },
  { name: "FLIPNAC 2ML SOLUTION" },
  { name: "HEPTOWITT INJ" },
  { name: "IMMUVENT INJ" },
  { name: "IVPARA 1GM INFUSION" },
  { name: "MEROSWIFT 1GM INJ" },
  { name: "MEROSWIFT PLUS INJ" },
  { name: "NUZOLID IV" },
  { name: "PIPRASWIFT INJ" },
  { name: "REBIROX IV INJ" },
  { name: "TAZOSWIFT INJ" },
  { name: "TECNOCEF INJ" },
  { name: "UZIDAC A INJ" },
  { name: "WISOPRIDE INJ" },
];
